# Generated by Django 3.2 on 2024-01-17 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonedata',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='phonedata',
            name='storage',
        ),
    ]
