# Generated by Django 3.2 on 2024-01-17 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20240117_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamedata')),
                ('phonecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.phonedata')),
            ],
        ),
    ]
