# Generated by Django 3.2 on 2024-01-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20240117_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
