# Generated by Django 3.2 on 2024-01-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='gamecategory',
            field=models.CharField(choices=[('FPS', 'FPS'), ('音楽ゲーム', '音楽ゲーム'), ('オープンワールド', 'オープンワールド'), ('パズルゲーム', 'パズルゲーム')], max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
